export interface IUserDataApiResponse {
  mailresponse?: string,
  statuscode?: number,
  status?: string,
  userdata?: IUserData[]
}

export interface IUserData {
  userid?: string,
  email?: string,
  pwd?: string,
  myreferid?: string,
  referralid?: string,
  fname?: string,
  lname?: string,
  phonenum?: string,
  pin?: string,
  tpin?: string,
  dpurl?: string,
  verifyemail?: string,
  verifyphone?: string,
  accounttype?: string,
  accountnumber?: string,
  accountnumberb?: string,
  amountngn?: string,
  amountbtc?: string,
  accountlimit?: string,
  bvnverified?: string,
  valididfile?: string,
  valididverify?: string,
  country?: string,
  state?: string,
  address?: string,
  apikey?: string,
  blockstatus?: string,
  datecreated?: string,
  datemodified?: string,
  datelastlogin?: string,
}
